source 'https://rubygems.org'

gem 'embork'

# To include compass, include the gem, and use the 'use_framework' DSL in the
# Borkfile.
#
# gem 'compass'

# To include bootstrap, include the gem, and use the 'use_framework' DSL in the
# Borkfile.
#
# gem 'bootstrap-sass'

# Include the closure-compiler or uglifier gem to use either javascript
# compressor. They both have to be enabled through your Borkfile.
#
# gem 'closure-compiler'
